ARG baseImageVersion
FROM amazoncorretto:17.0.14-al2023 AS base
WORKDIR /app

RUN yum update -y && yum install -y findutils
COPY ./gradlew .
COPY ./gradle ./gradle
RUN ./gradlew tasks || echo ignored

COPY . .
RUN ./gradlew clean assemble --no-daemon
FROM eventuateio/eventuate-examples-docker-images-spring-example-base-image:$baseImageVersion
ARG serviceImageVersion
COPY --from=base /app/security-system-service-main/build/libs/security-system-service-main-$serviceImageVersion.jar service.jar
HEALTHCHECK --interval=3s --retries=20 CMD curl -f http://localhost:3001/actuator/health || exit 1
